modLoader="javafml" #mandatory
loaderVersion = "[0,)"
license="LGPL3"
[[mods]]
modId = "create_mechanical_extruder"
version = "${file.jarVersion}"
displayName = "Create Mechanical Extruder"
logoFile="logo.png"
description = '''
Gather blocks from fluid combinations.
'''

[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId = "create"
mandatory = true
versionRange="${create_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "mechanicals"
mandatory = true
versionRange="${mechanicals_range}"
ordering = "AFTER"
side = "BOTH"
