modLoader="javafml" #mandatory
loaderVersion = "[0,)"
license="LGPL3"
[[mods]]
modId = "create_mechanical_extruder"
version = "${file.jarVersion}"
displayName = "Create Mechanical Extruder"
logoFile="logo.png"
description = '''
Gather blocks from fluid combinations.
'''

[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId = "create"
mandatory = true
versionRange="[6.0.2,6.1.0)"
ordering = "AFTER"
side = "BOTH"
